#!/usr/bin/env python3
"""
tools/gcloud/host-bridge.py — runs ON THE macOS HOST.

Exposes the host's authenticated Google Cloud SDK (gcloud / gsutil / bq) as an
HTTP service on :18187 so the disposable Docker container — which has no gcloud
and no Google credentials — can drive GCP through the Mac's logged-in account.

Why a bridge instead of installing gcloud in the container:
  * `gcloud auth login` is interactive (opens a browser) — only practical on the
    Mac. Keeping auth on the host means the container never holds Google
    credentials and stays disposable. Same philosophy as the qmd / transcribe /
    voice / browser bridges (host.docker.internal:18181/18185/18186/18184).

Token-gated via GCLOUD_BRIDGE_TOKEN (generated by the setup script into
.secrets/gcloud-bridge.env, which the container reads via the bind-mount).

SECURITY MODEL: this grants the container the SAME GCP power the host's gcloud
login has. Controls: (1) bearer token, (2) bound to the docker host only,
(3) argv is executed WITHOUT a shell (subprocess list form) so there is no shell
injection, (4) only an allowlisted set of SDK binaries can be invoked
({gcloud, gsutil, bq}). It is NOT a sandbox against destructive gcloud commands —
the caller is trusted exactly as much as a local operator running gcloud.

Install/keep-alive: tools/gcloud/host-bridge-setup.sh (launchd).

Endpoints:
  GET  /health
       -> {ok, tools:{gcloud,gsutil,bq}, account, project, port}
  POST /run  {tool?:"gcloud"|"gsutil"|"bq", args:[...], stdin?:str, timeout?:int}
       -> {ok, returncode, stdout, stderr, tool, argv}
"""
import os, sys, json, shutil, subprocess
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

PORT  = int(os.environ.get("GCLOUD_BRIDGE_PORT", "18187"))
TOKEN = os.environ.get("GCLOUD_BRIDGE_TOKEN", "")
DEFAULT_TIMEOUT = int(os.environ.get("GCLOUD_BRIDGE_TIMEOUT", "600"))

# Only these SDK CLIs may be invoked through the bridge.
ALLOWED_TOOLS = ("gcloud", "gsutil", "bq")

# Common Homebrew / SDK install locations to fall back on if not on PATH.
_SDK_DIRS = [
    "/opt/homebrew/bin",
    "/opt/homebrew/share/google-cloud-sdk/bin",
    "/usr/local/bin",
    "/usr/local/share/google-cloud-sdk/bin",
    os.path.expanduser("~/google-cloud-sdk/bin"),
]

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# --- Per-agent credential isolation (multi-tenant) ------------------------------------------
# Each tenant token maps to its OWN CLOUDSDK_CONFIG dir (its own gcloud identity) + a readonly
# flag. An agent's token can ONLY use its own config — credentials are never shared or reused
# across agents. The default env TOKEN keeps the host's default config (back-compat default).
# Tenants are loaded from .secrets/gcloud-tenants.json: [{token, config, readonly, label}].
def _load_tenants():
    tenants = {}
    if TOKEN:
        tenants[TOKEN] = {"config": None, "readonly": False, "label": "default"}
    path = os.environ.get("GCLOUD_BRIDGE_TENANTS") or os.path.join(_REPO, ".secrets", "gcloud-tenants.json")
    try:
        with open(path) as fh:
            for t in json.load(fh):
                tok = t.get("token")
                if tok:
                    tenants[tok] = {
                        "config": os.path.expanduser(t["config"]) if t.get("config") else None,
                        "readonly": bool(t.get("readonly", False)),
                        "label": t.get("label", "agent"),
                    }
    except FileNotFoundError:
        pass
    except Exception as e:
        print(f"WARN: could not load tenants from {path}: {e}", flush=True)
    return tenants

TENANTS = _load_tenants()

# Read-only enforcement reuses the agent guard's cloud policy (one source of truth).
try:
    sys.path.insert(0, os.path.join(_REPO, "platform", "agentd", "hooks"))
    from guard import decide_cloud_readonly as _decide_ro
except Exception:
    _decide_ro = None


def _resolve_tool(tool):
    """Absolute path to an allowlisted SDK binary, or None if not found."""
    if tool not in ALLOWED_TOOLS:
        return None
    p = shutil.which(tool)
    if p:
        return p
    for d in _SDK_DIRS:
        cand = os.path.join(d, tool)
        if os.path.exists(cand):
            return cand
    return None


def _run(tool, args, stdin, timeout, tenant=None):
    exe = _resolve_tool(tool)
    if not exe:
        raise RuntimeError(f"{tool} not installed on host — run tools/gcloud/host-bridge-setup.sh")
    if not isinstance(args, list) or not all(isinstance(a, str) for a in args):
        raise ValueError("args must be a list of strings")
    tenant = tenant or {}
    # Read-only enforcement (host-side, outside the container — defense in depth with the agent guard).
    if tenant.get("readonly") and _decide_ro is not None:
        ok, reason = _decide_ro(tool + " " + " ".join(args))
        if not ok:
            return {"ok": False, "returncode": 13, "stdout": "",
                    "stderr": f"[gcloud-bridge readonly] BLOCKED: {reason}", "tool": tool, "argv": args}
    # Per-agent credential: run with THIS tenant's CLOUDSDK_CONFIG (its own identity), never the host default.
    env = dict(os.environ)
    if tenant.get("config"):
        env["CLOUDSDK_CONFIG"] = tenant["config"]
    argv = [exe] + args
    proc = subprocess.run(
        argv,
        input=(stdin or None),
        capture_output=True,
        text=True,
        timeout=timeout or DEFAULT_TIMEOUT,
        env=env,
    )
    return {
        "ok": proc.returncode == 0,
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "tool": tool,
        "argv": args,
    }


def _quick(tool, args):
    """Best-effort single value for /health (never raises)."""
    try:
        r = _run(tool, args, None, 15)
        return r["stdout"].strip() if r["ok"] else None
    except Exception:
        return None


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):            # quiet; launchd captures stdout
        pass

    def _send(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _tenant(self):
        """Resolve the bearer token to its tenant (its own config + readonly), or None if unknown.
        Back-compat: if NO tenants are configured at all, allow with the host default config."""
        if not TENANTS:
            return {"config": None, "readonly": False, "label": "open"}
        auth = self.headers.get("Authorization", "")
        tok = auth[7:] if auth.startswith("Bearer ") else ""
        return TENANTS.get(tok)

    def do_GET(self):
        if self.path != "/health":
            return self._send(404, {"ok": False, "error": "not found"})
        tools = {t: bool(_resolve_tool(t)) for t in ALLOWED_TOOLS}
        account = _quick("gcloud", ["config", "get-value", "account"]) if tools["gcloud"] else None
        project = _quick("gcloud", ["config", "get-value", "project"]) if tools["gcloud"] else None
        self._send(200, {
            "ok": True,
            "tools": tools,
            "account": account or None,
            "project": project or None,
            "port": PORT,
        })

    def do_POST(self):
        tenant = self._tenant()
        if tenant is None:
            return self._send(401, {"ok": False, "error": "unauthorized (unknown agent token)"})
        if self.path != "/run":
            return self._send(404, {"ok": False, "error": "not found"})
        try:
            n = int(self.headers.get("Content-Length", "0"))
            req = json.loads(self.rfile.read(n) if n else b"{}")
            tool = req.get("tool", "gcloud")
            if tool not in ALLOWED_TOOLS:
                return self._send(400, {"ok": False,
                                        "error": f"tool must be one of {ALLOWED_TOOLS}"})
            res = _run(tool, req.get("args", []), req.get("stdin"),
                       int(req.get("timeout", DEFAULT_TIMEOUT)), tenant=tenant)
            return self._send(200, res)
        except subprocess.TimeoutExpired:
            self._send(504, {"ok": False, "error": "command timed out"})
        except ValueError as e:
            self._send(400, {"ok": False, "error": str(e)})
        except Exception as e:
            self._send(500, {"ok": False, "error": str(e)})


if __name__ == "__main__":
    have = ", ".join(f"{t}={'ok' if _resolve_tool(t) else 'MISSING'}" for t in ALLOWED_TOOLS)
    print(f"gcloud-bridge on :{PORT}  [{have}]", flush=True)
    ThreadingHTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
