#!/usr/bin/env python3
"""
wiki.py — deterministic ops for the LLM knowledge wiki (Karpathy-style, portable, zero-infra).

The LLM does the SEMANTIC work (ingest sources → write/curate pages, answer queries by
navigating links). This script does the MECHANICAL, VERIFIABLE parts so the model can't drift:
scaffold the layout, rebuild index.md, lint (orphans / stale / broken [[links]] / bad frontmatter),
scaffold a new page, append to the log. Stdlib + pyyaml only. Cross-platform.

Layout (under <dir>, default ./knowledge):
  raw/                    immutable source material (read, never edit)
  wiki/concepts/*.md      concept pages
  wiki/entities/*.md      entity pages
  wiki/sources/*.md       per-source summaries (point back to raw/)
  wiki/syntheses/*.md     cross-cutting rollups
  index.md                generated catalog            (wiki.py index)
  log.md                  append-only operation log    (wiki.py log "...")

Each wiki page has YAML frontmatter:
  title, type, created, updated, sources: [..], related: [[..]], confidence: high|medium|low, status: draft|verified|stale

Usage:
  wiki.py init   [dir]
  wiki.py index  [dir]
  wiki.py lint   [dir] [--stale-days 90]
  wiki.py new    [dir] --type concept --title "Attention Mechanism" [--sources raw/x.pdf]
  wiki.py log    [dir] "ingested raw/foo.md; updated 3 concept pages"
"""
import sys, os, re, argparse, datetime, pathlib

try:
    import yaml
except Exception:
    yaml = None

TYPES = ("concepts", "entities", "sources", "syntheses")
WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
REQUIRED_FM = ("title", "type", "status")


def _now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def split_frontmatter(text):
    """Return (frontmatter_dict_or_None, body). Tolerant of missing/broken frontmatter."""
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    raw = text[3:end].strip()
    body = text[end + 4:].lstrip("\n")
    if yaml is None:
        return {}, body
    try:
        return (yaml.safe_load(raw) or {}), body
    except Exception:
        return None, body  # broken frontmatter -> None signals a lint error


def wiki_pages(base):
    """Yield (path, type) for every wiki page."""
    for t in TYPES:
        d = base / "wiki" / t
        if d.is_dir():
            for p in sorted(d.glob("*.md")):
                yield p, t


def cmd_init(base, args):
    for d in ["raw", "wiki/concepts", "wiki/entities", "wiki/sources", "wiki/syntheses"]:
        (base / d).mkdir(parents=True, exist_ok=True)
    idx = base / "index.md"
    if not idx.exists():
        idx.write_text(f"# Knowledge Wiki — index\n\n_Generated by `wiki.py index`. Last: never._\n")
    log = base / "log.md"
    if not log.exists():
        log.write_text("# Wiki operation log\n\n")
    schema = base / "WIKI.md"
    if not schema.exists():
        schema.write_text(SCHEMA_DOC)
    print(f"Initialized knowledge wiki at {base}")
    print("  raw/ (sources) · wiki/{concepts,entities,sources,syntheses} · index.md · log.md · WIKI.md (schema)")


def cmd_index(base, args):
    """Rebuild index.md: a catalog grouped by type, titles from frontmatter."""
    lines = ["# Knowledge Wiki — index", "", f"_Generated by `wiki.py index` on {_now()}._", ""]
    total = 0
    for t in TYPES:
        pages = [(p, split_frontmatter(p.read_text(errors="ignore"))[0] or {}) for p, tt in wiki_pages(base) if tt == t]
        if not pages:
            continue
        lines.append(f"## {t.capitalize()} ({len(pages)})")
        for p, fm in pages:
            rel = p.relative_to(base).as_posix()
            title = fm.get("title") or p.stem
            conf = fm.get("confidence")
            status = fm.get("status")
            tag = " · ".join(x for x in [status, (f"conf:{conf}" if conf else None)] if x)
            lines.append(f"- [[{p.stem}]] — {title}" + (f"  _({tag})_" if tag else "") + f"  `{rel}`")
            total += 1
        lines.append("")
    (base / "index.md").write_text("\n".join(lines) + "\n")
    print(f"index.md rebuilt — {total} pages across {sum(1 for t in TYPES if any(tt==t for _,tt in wiki_pages(base)))} types.")


def cmd_lint(base, args):
    """Report orphans / stale / broken-links / bad-frontmatter. Exit 1 if any blocker."""
    pages = list(wiki_pages(base))
    by_stem = {p.stem: p for p, _ in pages}
    inbound = {p.stem: 0 for p, _ in pages}
    problems = {"bad_frontmatter": [], "missing_fields": [], "broken_links": [], "orphans": [], "stale": []}
    cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=args.stale_days)).strftime("%Y-%m-%d")

    for p, t in pages:
        text = p.read_text(errors="ignore")
        fm, body = split_frontmatter(text)
        rel = p.relative_to(base).as_posix()
        if fm is None:
            problems["bad_frontmatter"].append(rel); continue
        missing = [k for k in REQUIRED_FM if not fm.get(k)]
        if missing:
            problems["missing_fields"].append(f"{rel} (missing: {', '.join(missing)})")
        # links: count inbound + flag broken
        for tgt in WIKILINK.findall(text):
            key = tgt if tgt in by_stem else slug(tgt)
            if key in inbound:
                inbound[key] += 1
            elif key not in by_stem:
                problems["broken_links"].append(f"{rel} -> [[{tgt}]]")
        # stale: explicit status or old `updated`
        upd = str(fm.get("updated") or fm.get("created") or "")
        if fm.get("status") == "stale" or (upd and upd < cutoff):
            problems["stale"].append(f"{rel} (updated: {upd or 'unknown'})")

    for stem, n in inbound.items():
        if n == 0:
            problems["orphans"].append(by_stem[stem].relative_to(base).as_posix())

    print(f"Wiki lint — {len(pages)} pages\n")
    blockers = problems["bad_frontmatter"]
    for key, items in problems.items():
        if not items:
            continue
        mark = "❗" if key in ("bad_frontmatter",) else "·"
        print(f"{mark} {key.replace('_',' ')}: {len(items)}")
        for it in items[:20]:
            print(f"    {it}")
    if not any(problems.values()):
        print("clean ✓")
    sys.exit(1 if blockers else 0)


FOLDERS = {"concept": "concepts", "entity": "entities", "source": "sources", "synthesis": "syntheses"}


def cmd_new(base, args):
    if args.type not in FOLDERS:
        sys.exit("--type must be one of: " + ", ".join(FOLDERS))
    folder = FOLDERS[args.type]
    name = slug(args.title)
    path = base / "wiki" / folder / f"{name}.md"
    if path.exists():
        sys.exit(f"already exists: {path}")
    srcs = args.sources or []
    fm = [
        "---", f"title: {args.title}", f"type: {args.type}",
        f"created: {_now()}", f"updated: {_now()}",
        "sources: [" + ", ".join(srcs) + "]",
        "related: []", "confidence: medium", "status: draft", "---", "",
        f"# {args.title}", "",
        "<!-- Write the curated knowledge here. Cite raw/ sources. Link related pages with double-bracket wikilinks (the target filename without .md). -->", "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(fm))
    print(f"created {path.relative_to(base).as_posix()}")


def cmd_log(base, args):
    line = f"- {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%MZ')} — {args.message}\n"
    log = base / "log.md"
    with log.open("a") as f:
        f.write(line)
    print("logged.")


SCHEMA_DOC = """# Knowledge Wiki — schema & workflow

This is an LLM-maintained knowledge base (Karpathy-style). You write and curate it; `wiki.py`
handles the mechanical parts. Keep it traceable: every claim links back to a `raw/` source.

## Layout
- `raw/` — immutable source material. READ, never edit.
- `wiki/concepts/` — concept pages (one idea each).
- `wiki/entities/` — people/orgs/systems.
- `wiki/sources/` — one summary page per ingested raw source (points back to `raw/`).
- `wiki/syntheses/` — cross-cutting rollups that connect concepts.
- `index.md` — generated catalog (`wiki.py index`). Read this FIRST to navigate.
- `log.md` — append-only operation log.

## Page frontmatter (required)
```
---
title: ...
type: concept|entity|source|synthesis
created: YYYY-MM-DD
updated: YYYY-MM-DD
sources: [raw/foo.pdf, raw/bar.md]
related: [[other-page-stem]]
confidence: high|medium|low
status: draft|verified|stale
---
```
Link pages with `[[page-stem]]` (the filename without `.md`).

## Operations
- **ingest** (a new `raw/` source): create a `wiki/sources/<src>.md` summary, then cascade —
  update/create the concept & entity pages it touches, link them, then `wiki.py index` and `wiki.py log`.
- **query**: read `index.md`, follow `[[links]]` to the relevant pages, answer with citations to `raw/`.
- **lint** (`wiki.py lint`): fix broken links, orphans, stale pages, missing frontmatter.
"""


def main():
    ap = argparse.ArgumentParser(prog="wiki.py")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("init", "index"):
        s = sub.add_parser(name); s.add_argument("dir", nargs="?", default="knowledge")
    s = sub.add_parser("lint"); s.add_argument("dir", nargs="?", default="knowledge"); s.add_argument("--stale-days", type=int, default=90)
    s = sub.add_parser("new"); s.add_argument("dir", nargs="?", default="knowledge"); s.add_argument("--type", required=True); s.add_argument("--title", required=True); s.add_argument("--sources", nargs="*")
    s = sub.add_parser("log"); s.add_argument("dir", nargs="?", default="knowledge"); s.add_argument("message")
    args = ap.parse_args()
    base = pathlib.Path(args.dir).resolve()
    if args.cmd != "init" and not base.exists():
        sys.exit(f"no wiki at {base} — run `wiki.py init {args.dir}` first")
    {"init": cmd_init, "index": cmd_index, "lint": cmd_lint, "new": cmd_new, "log": cmd_log}[args.cmd](base, args)


if __name__ == "__main__":
    main()
